export const environment = {
  production: true,
  url: 'https://apiadmincetec.sloppy.zone/',
  urlLibreta: 'https://matcetec.superatemexico.com/',
	libreta_URI: 'http://cetec.superatemexico.com/#',
	vendor: 'ACL Systems SA de CV',
  idTutor: '5afade18be6da5001b81e59f',
	versionCheckURL: 'version.json',
	instanceName: 'cetec',
	instanceTitle: 'CETEC',
	siteName: 'matcetec.superatemexico.com',
	footer: 'CETEC',
	captchaSiteKey: '6LczNrUUAAAAAMxj3XKiG9Nv7wOwBVpZiecKqiFX',
	publicKey: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBTldjcE5ZQlhjN2tEK3dNZC9HOGlGU0xIc1lJWlZuOQp0SWE1WjB2RDVxNFVwUG8wdDQwS21XVXZqVlVQWHZtM2FydUJOcjI3dmtoTHpvUmgrUDU0eElNQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=',
	logo: '/assets/img/grupocetec.jpg',
	color: 'info',
	eventColor: '#16A2B8',
	colorEvents: ['#16A2B8', '#04B45F', '#BE1C1F', '#E6E6E6'],
	textColor: '#FFFFFF',
	selfRegister: true,
	emailSupport: 'soporte@superatemexico.com'
};
